"""migracion record

Revision ID: 145a9dae2d75
Revises: 69f131a64bf2
Create Date: 2026-03-18 23:04:38.294501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145a9dae2d75'
down_revision = '69f131a64bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    # ### end Alembic commands ###
